### ISSUE TITLE
Handling fail POS only @ Signature required prompt

### ISSUE THREAD

**Issue by MatthewVisser** [Yortw/Yort.Eftpos.Verifone.PosLink#1]
Ignore me, the way I was restarting the app was causing the issue.

**Comment by Yortw** [comment]
No problem, glad you solved it!

PS: I had a few power failure situations where the terminal didn't behave as the documents described. I think one of them was where the PC power failed but the pinpad didn't - the pinpad held it's socket open for about 10 minutes which was longer than the PC restart + reconnect/retry interval... with my solution it would then prompt the user to retry and if they retried enough times it worked, but 10 minutes is a long time to wait and most users will give up. When I complained to the company supplying the hardware they basically said it was a known issue and that was fine, they would certify the solutions so long as it gave the user the option to keep retrying (or not). Happy to help with any issues I can, but be aware that sometimes the device/docs don't line up and it just is what it is.
