### ISSUE TITLE
Pax A920 Pro support

### ISSUE THREAD

**Issue by reader-man** [Yortw/Yort.Eftpos.Verifone.PosLink#4]
hi,
does ur repo support the "Pax A920 Pro"
https://youtube.com/watch?v=wLKdSz-UQmA

**Comment by Yortw** [comment]
Hi,
I'm afraid I'm not familiar with that model and so don't know. Verifone (at least in NZ where I am) have multiple solutions they load onto various devices. If that one runs, or can be loaded with, the "POSLink" protocol software, then yes, this package should be compatible. However that looks more like the "CM5" (Carbon Mobile 5) devices we have here in NZ, which are a newer model of pinpad running Android. These do not usually use POSLink and instead you need to get the "Verifone psdk" and work with that (there are versions for UWP, Android and iOS - I am not sure there is a Windows version that is not UWP). Last I checked you had to sign up with Verfione to get access to that SDK. Distribution of that sdk is somewhat more tightly controlled than their previous systems.

**Comment by reader-man** [comment]
if i want u to develop the same functionality that u did in this project, but for the PAX a920 using USB + WiFi + Bluetooth.
How much it will cost, and how much time?

**Comment by Yortw** [comment]
Oh, that's a nice offer but I'm afraid I'm not offering contract services at this time, sorry.

**Comment by reader-man** [comment]
thanks a lot.
